force attacker wallet to recognize new coins
Need to rescan the utxos in the attacker wallet to avoid:

Exception: Attacker wallet has no confirmed UTXOs to spend